const BASE_URL = 'api.qr1xmovie.students.nomoredomainsrocks.ru';
const MOVIES_URL = 'https://localhost:3000';
const SUCCESSFUL_CODE = 200;
const INVALID_CODE = 400;

const movies = [
    {
      country: 'США',
      director: 'Фрэнк Дарабонт',
      duration: 189,
      year: 199,
      description: 'Пол Эджкомб — начальник блока смертников в тюрьме «Холодная гора», каждый из узников которого однажды проходит «зеленую милю» по пути к месту казни. Пол повидал много заключённых и надзирателей за время работы. Однако гигант Джон Коффи, обвинённый в страшном преступлении, стал одним из самых необычных обитателей блока.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      trailer: 'https://www.youtube.com/watch?v=TODt_q-_4C4',
      nameRU: 'Зеленая миля',
      nameEN: 'The Green Mile',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      movieId: 1,
      saved: false,
    },
    {
      country: 'Франция',
      director: 'Оливье Накаш',
      duration: 112,
      year: 2011,
      description: 'Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      trailer: 'https://www.youtube.com/watch?v=m95M-I7Ij0o',
      nameRU: '1+1',
      nameEN: 'Intouchables',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      movieId: 2,
      saved: true,
    },
    {
      country: 'США',
      director: 'Дэвид Финчер',
      duration: 139,
      year: 1999,
      description: 'Сотрудник страховой компании страдает хронической бессонницей и отчаянно пытается вырваться из мучительно скучной жизни. Однажды в очередной командировке он встречает некоего Тайлера Дёрдена — харизматического торговца мылом с извращенной философией. Тайлер уверен, что самосовершенствование — удел слабых, а единственное, ради чего стоит жить, — саморазрушение.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      trailer: 'https://www.youtube.com/watch?v=C7-7qQ61QHU',
      nameRU: 'Бойцовский клуб',
      nameEN: 'Fight Club',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      movieId: 3,
      saved: true,
    },
    {
      country: 'США',
      director: 'Гай Ричи',
      duration: 113,
      year: 2019,
      description: 'Один ушлый американец ещё со студенческих лет приторговывал наркотиками, а теперь придумал схему нелегального обогащения с использованием поместий обедневшей английской аристократии и очень неплохо на этом разбогател. Другой пронырливый журналист приходит к Рэю, правой руке американца, и предлагает тому купить киносценарий, в котором подробно описаны преступления его босса при участии других представителей лондонского криминального мира — партнёра-еврея, китайской диаспоры, чернокожих спортсменов и даже русского олигарха.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      trailer: 'https://www.youtube.com/watch?v=dABPCMxu074',
      nameRU: 'Джентльмены',
      nameEN: 'The Gentlemen',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      movieId: 4,
      saved: false,
    },
    {
      country: 'США',
      director: 'Фрэнк Дарабонт',
      duration: 189,
      year: 199,
      description: 'Пол Эджкомб — начальник блока смертников в тюрьме «Холодная гора», каждый из узников которого однажды проходит «зеленую милю» по пути к месту казни. Пол повидал много заключённых и надзирателей за время работы. Однако гигант Джон Коффи, обвинённый в страшном преступлении, стал одним из самых необычных обитателей блока.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      trailer: 'https://www.youtube.com/watch?v=TODt_q-_4C4',
      nameRU: 'Зеленая миля',
      nameEN: 'The Green Mile',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      movieId: 5,
      saved: false,
    },
    {
      country: 'Франция',
      director: 'Оливье Накаш',
      duration: 112,
      year: 2011,
      description: 'Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      trailer: 'https://www.youtube.com/watch?v=m95M-I7Ij0o',
      nameRU: '1+1',
      nameEN: 'Intouchables',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      movieId: 6,
      saved: false,
    },
    {
      country: 'США',
      director: 'Дэвид Финчер',
      duration: 139,
      year: 1999,
      description: 'Сотрудник страховой компании страдает хронической бессонницей и отчаянно пытается вырваться из мучительно скучной жизни. Однажды в очередной командировке он встречает некоего Тайлера Дёрдена — харизматического торговца мылом с извращенной философией. Тайлер уверен, что самосовершенствование — удел слабых, а единственное, ради чего стоит жить, — саморазрушение.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      trailer: 'https://www.youtube.com/watch?v=C7-7qQ61QHU',
      nameRU: 'Бойцовский клуб',
      nameEN: 'Fight Club',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      movieId: 7,
      saved: true,
    },
    {
      country: 'США',
      director: 'Гай Ричи',
      duration: 113,
      year: 2019,
      description: 'Один ушлый американец ещё со студенческих лет приторговывал наркотиками, а теперь придумал схему нелегального обогащения с использованием поместий обедневшей английской аристократии и очень неплохо на этом разбогател. Другой пронырливый журналист приходит к Рэю, правой руке американца, и предлагает тому купить киносценарий, в котором подробно описаны преступления его босса при участии других представителей лондонского криминального мира — партнёра-еврея, китайской диаспоры, чернокожих спортсменов и даже русского олигарха.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      trailer: 'https://www.youtube.com/watch?v=dABPCMxu074',
      nameRU: 'Джентльмены',
      nameEN: 'The Gentlemen',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      movieId: 8,
      saved: true,
    },
    {
      country: 'США',
      director: 'Фрэнк Дарабонт',
      duration: 189,
      year: 199,
      description: 'Пол Эджкомб — начальник блока смертников в тюрьме «Холодная гора», каждый из узников которого однажды проходит «зеленую милю» по пути к месту казни. Пол повидал много заключённых и надзирателей за время работы. Однако гигант Джон Коффи, обвинённый в страшном преступлении, стал одним из самых необычных обитателей блока.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      trailer: 'https://www.youtube.com/watch?v=TODt_q-_4C4',
      nameRU: 'Зеленая миля',
      nameEN: 'The Green Mile',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      movieId: 9,
      saved: false,
    },
    {
      country: 'Франция',
      director: 'Оливье Накаш',
      duration: 112,
      year: 2011,
      description: 'Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      trailer: 'https://www.youtube.com/watch?v=m95M-I7Ij0o',
      nameRU: '1+1',
      nameEN: 'Intouchables',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      movieId: 10,
      saved: true,
    },
    {
      country: 'США',
      director: 'Дэвид Финчер',
      duration: 139,
      year: 1999,
      description: 'Сотрудник страховой компании страдает хронической бессонницей и отчаянно пытается вырваться из мучительно скучной жизни. Однажды в очередной командировке он встречает некоего Тайлера Дёрдена — харизматического торговца мылом с извращенной философией. Тайлер уверен, что самосовершенствование — удел слабых, а единственное, ради чего стоит жить, — саморазрушение.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      trailer: 'https://www.youtube.com/watch?v=C7-7qQ61QHU',
      nameRU: 'Бойцовский клуб',
      nameEN: 'Fight Club',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      movieId: 11,
      saved: false,
    },
    {
      country: 'США',
      director: 'Гай Ричи',
      duration: 113,
      year: 2019,
      description: 'Один ушлый американец ещё со студенческих лет приторговывал наркотиками, а теперь придумал схему нелегального обогащения с использованием поместий обедневшей английской аристократии и очень неплохо на этом разбогател. Другой пронырливый журналист приходит к Рэю, правой руке американца, и предлагает тому купить киносценарий, в котором подробно описаны преступления его босса при участии других представителей лондонского криминального мира — партнёра-еврея, китайской диаспоры, чернокожих спортсменов и даже русского олигарха.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      trailer: 'https://www.youtube.com/watch?v=dABPCMxu074',
      nameRU: 'Джентльмены',
      nameEN: 'The Gentlemen',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      movieId: 12,
      saved: false,
    },
    {
      country: 'США',
      director: 'Фрэнк Дарабонт',
      duration: 189,
      year: 199,
      description: 'Пол Эджкомб — начальник блока смертников в тюрьме «Холодная гора», каждый из узников которого однажды проходит «зеленую милю» по пути к месту казни. Пол повидал много заключённых и надзирателей за время работы. Однако гигант Джон Коффи, обвинённый в страшном преступлении, стал одним из самых необычных обитателей блока.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      trailer: 'https://www.youtube.com/watch?v=TODt_q-_4C4',
      nameRU: 'Зеленая миля',
      nameEN: 'The Green Mile',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/acb932eb-c7d0-42de-92df-f5f306c4c48e/1920x',
      movieId: 13,
      saved: false,
    },
    {
      country: 'Франция',
      director: 'Оливье Накаш',
      duration: 112,
      year: 2011,
      description: 'Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      trailer: 'https://www.youtube.com/watch?v=m95M-I7Ij0o',
      nameRU: '1+1',
      nameEN: 'Intouchables',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/c4cb60a9-6743-47df-9390-4707fd857481/1920x',
      movieId: 14,
      saved: false,
    },
    {
      country: 'США',
      director: 'Дэвид Финчер',
      duration: 139,
      year: 1999,
      description: 'Сотрудник страховой компании страдает хронической бессонницей и отчаянно пытается вырваться из мучительно скучной жизни. Однажды в очередной командировке он встречает некоего Тайлера Дёрдена — харизматического торговца мылом с извращенной философией. Тайлер уверен, что самосовершенствование — удел слабых, а единственное, ради чего стоит жить, — саморазрушение.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      trailer: 'https://www.youtube.com/watch?v=C7-7qQ61QHU',
      nameRU: 'Бойцовский клуб',
      nameEN: 'Fight Club',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/ed5f8af5-a6f0-4ec3-80bd-8380351bf722/1920x',
      movieId: 15,
      saved: true,
    },
    {
      country: 'США',
      director: 'Гай Ричи',
      duration: 113,
      year: 2019,
      description: 'Один ушлый американец ещё со студенческих лет приторговывал наркотиками, а теперь придумал схему нелегального обогащения с использованием поместий обедневшей английской аристократии и очень неплохо на этом разбогател. Другой пронырливый журналист приходит к Рэю, правой руке американца, и предлагает тому купить киносценарий, в котором подробно описаны преступления его босса при участии других представителей лондонского криминального мира — партнёра-еврея, китайской диаспоры, чернокожих спортсменов и даже русского олигарха.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      trailer: 'https://www.youtube.com/watch?v=dABPCMxu074',
      nameRU: 'Джентльмены',
      nameEN: 'The Gentlemen',
      thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/bc6b84c7-52ce-49f6-85fc-247b1f36a5c6/1920x',
      movieId: 16,
      saved: false,
    },
  ];

export {
  BASE_URL,
  MOVIES_URL,
  SUCCESSFUL_CODE,
  INVALID_CODE,
  movies
};
